# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jordan Sucher
tagline:          
description:      'Creative Technologist. I ride bikes sometimes. Based in Brooklyn, NY.'
url:              https://jordansucher.github.io
baseurl:          "/"

author:
  name:           'Jordan Sucher'
  url:            https://jordansucher.github.io

paginate:         5
plugins: [jekyll-paginate, jekyll-gist]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JordanSucher
